[package]
name = "natrix-compiler"
version = "0.1.0"
edition = "2024"

[dependencies]
natrix-runtime = { path = "../natrix-runtime" }

[dev-dependencies]
test-utils = { path = "../test-utils" }

[[test]]
name = "golden_tests"
harness = false
