#[derive(Debug, Copy, Clone, Eq, PartialEq)]
pub enum TokenType {
    Eof,
    Whitespace,
    Comment,
    KwFalse,
    KwFun,
    KwNull,
    KwPrint,
    KwReturn,
    KwTrue,
    KwVar,
    Identifier,
    IntLiteral,
    FloatLiteral,
    LParen,
    RParen,
    LBrace,
    RBrace,
    Plus,
    Minus,
    Star,
    Slash,
    Percent,
    Or,
    And,
    Eq,
    Ne,
    Lt,
    Le,
    Gt,
    Ge,
    Bang,
    Comma,
    Semicolon,
    Assign,
}

pub const KEYWORDS: &[(&str, TokenType)] = &[
    ("false", TokenType::KwFalse),
    ("fun", TokenType::KwFun),
    ("null", TokenType::KwNull),
    ("print", TokenType::KwPrint),
    ("return", TokenType::KwReturn),
    ("true", TokenType::KwTrue),
    ("var", TokenType::KwVar),
];
