#[derive(Debug, Copy, Clone, Eq, PartialEq)]
pub enum TokenType {
    Eof,
    Whitespace,
    Comment,
    KwBreak,
    KwContinue,
    KwElse,
    KwFalse,
    KwFun,
    KwIf,
    KwNull,
    KwReturn,
    KwTrue,
    KwVar,
    KwWhile,
    Identifier,
    IntLiteral,
    FloatLiteral,
    StringLiteral,
    LParen,
    RParen,
    LBrace,
    RBrace,
    Plus,
    Minus,
    Star,
    Slash,
    Percent,
    Or,
    And,
    Eq,
    Ne,
    Lt,
    Le,
    Gt,
    Ge,
    Bang,
    Comma,
    Semicolon,
    Assign,
}

pub const KEYWORDS: &[(&str, TokenType)] = &[
    ("break", TokenType::KwBreak),
    ("continue", TokenType::KwContinue),
    ("else", TokenType::KwElse),
    ("false", TokenType::KwFalse),
    ("fun", TokenType::KwFun),
    ("if", TokenType::KwIf),
    ("null", TokenType::KwNull),
    ("return", TokenType::KwReturn),
    ("true", TokenType::KwTrue),
    ("var", TokenType::KwVar),
    ("while", TokenType::KwWhile),
];
